postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
gitlab:
  image: andreasknoepfle/owlnest
  links:
   - redis:redisio
   - postgresql:postgresql
   - owldiff
  ports:
   - "80:80"
   - "22:22"
redis:
  image: sameersbn/redis:latest
owldiff:
  image: andreasknoepfle/owldiff-service
